ablate_clean_setup: true
audiocaps: false
batch_size: 32
batch_size_eval: 32
checkpoints_path: checkpoints
compile: false
data_path: data
devices: auto
initial_tau: 0.05
load_ckpt_path: null
logging: false
max_epochs: 20
max_lr: 2.0e-05
min_lr: 1.0e-07
n_workers: 8
rampdown_epochs: 15
resume_ckpt_path: null
roberta_base: false
s_patchout_f: 4
s_patchout_t: 40
seed: 21208
tau_trainable: false
test: true
train: true
training_mode: transformer
warmup_epochs: 1
wavcaps: false
